# Generated by Django 5.1.5 on 2025-01-25 08:39

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=600)),
                ("email", models.EmailField(max_length=600)),
                ("subject", models.CharField(max_length=1000)),
                ("message", models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=600)),
                ("category", models.CharField(max_length=600)),
                (
                    "image",
                    models.FileField(
                        upload_to="images/posts",
                        validators=[myapp.models.validate_file_type],
                    ),
                ),
                ("content", models.CharField(max_length=100000)),
                (
                    "time",
                    models.CharField(
                        blank=True, default="25 January 2025", max_length=100
                    ),
                ),
                ("likes", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                (
                    "time",
                    models.CharField(
                        blank=True, default="25 January 2025", max_length=100
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.post"
                    ),
                ),
            ],
        ),
    ]
